# Generated by Django 5.1.1 on 2024-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('locationid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('applicant', models.CharField(max_length=100)),
                ('facility_type', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('permit', models.CharField(max_length=50)),
            ],
        ),
    ]
