# Generated by Django 5.1.1 on 2024-09-07 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_foodtruck_id_alter_foodtruck_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
