# Generated by Django 5.1.1 on 2024-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_foodtruck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='facility_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='permit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
