# Generated by Django 5.1.1 on 2024-09-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_foodtruck_address_alter_foodtruck_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtruck',
            old_name='applicant',
            new_name='Applicant',
        ),
        migrations.RenameField(
            model_name='foodtruck',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='foodtruck',
            old_name='longitude',
            new_name='Longitude',
        ),
    ]
