# Generated by Django 5.1.1 on 2024-09-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_applicant_foodtruck_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtruck',
            old_name='address',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='foodtruck',
            name='facility_type',
        ),
    ]
